api_platform:
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Qiita/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
